server:
  port: 8080


app:
    profile: ${spring.profiles.active}
    
spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url:  jdbc:mysql://database-1.c6x9ym2ncfzc.us-east-2.rds.amazonaws.com:3306/mutant
    username:  mutantuser
    password:  ThePassword 
    driver-class-name:  com.mysql.jdbc.Driver

       